SOS_TOKEN = "<SOS>"  # Start-of-sequence token
EOS_TOKEN = "<EOS>"  # End-of-sequence token
VALIDATION_SPLIT = "val"
TRAIN_SPLIT = "train"
TEST_SPLIT = "test"
SPLITS = [TRAIN_SPLIT, VALIDATION_SPLIT, TEST_SPLIT]
PREPROCESSED_MUQ_ENCODER = "preprocessed_muq"
PREPROCESSED_MUQ_ENCODER_TEMPORAL_DOWNSAMPLING = (
    "preprocessed_muq_temporal_downsampling"
)
CNN_ENCODER = "cnn"
MUQ_ENCODER = "muq"
VALID_ENCODERS = [
    PREPROCESSED_MUQ_ENCODER,
    CNN_ENCODER,
    MUQ_ENCODER,
    PREPROCESSED_MUQ_ENCODER_TEMPORAL_DOWNSAMPLING,
]
WORD_LEVEL_TOKENISER = "word"
MID_LEVEL_TOKENISER = "medium"

PRECOMPUTED_ENCODERS = {
    PREPROCESSED_MUQ_ENCODER,
    PREPROCESSED_MUQ_ENCODER_TEMPORAL_DOWNSAMPLING,
}

PROJECT_NAME = "HookKernModel"
